#!/bin/bash
#
# bashCMS用reST -> html変換
#
# written by R. Ueda (USP友の会)

# The MIT License
#
# Copyright (C) 2012 Ryuichi Ueda
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

tmp=/tmp/$$

################################
#インデントの数を数えるpython片
# 8文字インデント決め打ち
cat << FIN > $tmp-count-indent
#!/usr/bin/python
import sys

for line in sys.stdin:
	line = line.rstrip()
	c = 0
	for ch in line:
		if ch == " ": c+=1
		elif ch == "\t": c+=8
		else: break
		
	print c, line
FIN

#################################
#インデントの個数をあたまにつける
cat "$1"			|
python $tmp-count-indent	|
#################################
#h1の処理（最初の三行決め打ち）
awk 'NR==2{gsub(/^[0-9]* /,"",$0);print "0 <h1>"$0"</h1>"}
	NR>=4{print}'		|
#################################
#h2の処理
awk '{
	if($0~/^[0-9]* ==*$/){
		gsub(/^[0-9]* /,"",a);print "0 <h2>"a"</h2>";
		a="";$0=""
	};
	if(a!=""){print a};a = $0}
	END{print a}'		|
#################################
#h3の処理
awk '{
	if($0~/^[0-9]* --*$/){
		gsub(/^[0-9]* /,"",a);print "0 <h3>"a"</h3>";
		a="";$0=""
	};
	if(a!=""){print a};a = $0}
	END{print a}'			|
#################################
# 強調の処理
sed 's;\*\(..*\)\*;<strong>\1</strong>;g'	|
#################################
# URLの処理
sed 's/`\([^<]*\)`_/`\1 <\1>`_/g'					|
sed 's;`\(..*\) <\(..*\)>`_;<a href="\2" target="_blank">\1</a>;g'	|
#################################
#リストの処理
#1: ulをつける
awk 'BEGIN{ind=0}
{
	n = $1;
	gsub(/^[0-9]* /,"",$0);
	if($0~/^[ \t]*\*/){
		while(ind < n){ printf("%d ",ind);for(i=0;i<ind;i++){printf(" ")};print "<ul>"; ind += 8}
		while(ind > n){ printf("%d ",ind);for(i=0;i<ind-8;i++){printf(" ")};print "</ul>"; ind -= 8}
	}
	print n,$0;
	ind = n
}'				|
#2:*をliに変換
sed -e 's;^\([0-9][0-9]*\)\([ \t][ \t]*\)\*\(..*\)$;\1\2<li>\3</li>;'	|
#################################
# imageの処理
awk 'BEGIN{flag=0}
{
	if($1==0 && flag==0){
		if($0~/.. image::/){file = $NF;flag=1}
		else{print}
	}
	else if($1==0 && flag==1){
		if(width!=""){w = "width=\""width"\""}else{w = ""}
		if(href==""){
			print "0 <img src=\"" file "\" " w" />"
		}		
		else{
			print "0 <a href=\"" href "\" target=\"_blank\">"
			print "0 <img"
			print "0 src=\"" file "\" "w" /></a>"
		}		

		flag=0;href="";width="";file="";
		print $0
	}
	else if($1!=0 && flag==0){print}
	else{
		if($0~/:href:/){href=$NF}
		else if($0~/:width:/){width=$NF}
	}
}'		|
#################################
# code-blockの処理
awk 'BEGIN{flag=0;wtn=0}
{
	n = $1;gsub(/^[0-9]* /,"",$0);
	if(n==0 && flag==0){
		if($0~/^.. code-block::/){
			flag=1;wtn=0;
			printf("0 <pre class=\"brush: %s\">\n",$NF);
		}
		else{print n,$0}
	}
	else if(n==0 && flag==1){
		if(wtn==1){
			print "0 </pre>";
			flag=0;
			print n,$0;
		}
	}
	else if(n!=0 && flag==0){print n,$0}
	else{gsub(/^[0-9]* /,"",$0);print n,$0;wtn=1}
}END{if(flag==1){print "0 </pre>"}}'		|
#################################
# インデントの数字を消す
sed 's/^[0-9]* //'	|
#################################
# 改行
awk '{if(NF==0){print "<br />"}else{print}}'


rm -f $tmp-*
